export type Locale='en'|'de';
export const content={
de:{
lang:'de',switchLabel:'EN',switchHref:'/en/',nav:['Leistungen','Über uns','Datenmodell'],contact:'Kontakt',
hero:{kicker:'01 / Stammdatenmanagement',title:['Stammdaten.','Prozesse.','Verlässliche','Geschäftsbeziehungen.'],intro:'PhySolution ist eine technische Unternehmensberatung und Projektmanagement-Boutique mit über 25 Jahren Erfahrung im Stammdatenmanagement.',since:'SEIT 1996 · GROß-GERAU',cta:'[ Leistungen entdecken ]'},
services:{kicker:'02 / Leistungen & Kompetenzen',title:['Daten verstehen.','Prozesse verbessern.'],intro:'Unsere Kernkompetenz ist das Geschäftspartner-Stammdatenmanagement — von MDM und Data Quality bis zu Governance, Analytics und Golden Records.',items:[['Geschäftspartner-Stammdaten','Prozessoptimierung'],['Data Quality & MDM','Qualität & Konsolidierung'],['Data Analytics','MS-SQL · Power BI · MS Office'],['Golden Records & Matching','Daten zusammenführen'],['Data Governance','Compliance & Governance'],['ERP & Web Integration','Prozesse & eCommerce'],['Identität & Fraud Prevention','Prüfungen & Risikodaten'],['Technologie- & Know-how-Datenbanken','Datenbanken & Wissenssysteme']]},
about:{kicker:'03 / Über PhySolution',title:['Über 25 Jahre','Erfahrung mit','wertvollen Daten.'],paragraphs:['Die PhySolution GmbH wurde 1996 von Dr. Roland Goschke, Dr. Matthias Drodt und Dr. Michael Speckmann in Groß-Gerau gegründet.','Als eine der ersten privatwirtschaftlichen Technologietransferberatungen entwickelte das Unternehmen bereits früh Technologie- und Experten-Datenbanken.','Mit dem Internet-Boom Ende der 1990er-Jahre wurde die Prozessberatung rund um Stammdaten- und Antragsmanagement zu einem wesentlichen Geschäftsbereich.','Heute berät PhySolution zu Stammdatenprozessen, Stammdatenkonsolidierung, Datenbankkonsolidierung sowie allen Fragen des Geschäftspartner-Datenmanagements.'],history:[['1996','Gründung der PhySolution GmbH in Groß-Gerau.'],['1997','Veröffentlichung der Datenbanken „Know-how Germany“ und „Know-how Professional“.'],['Heute','Beratung und Umsetzung im modernen Stammdatenmanagement.']]},
model:{kicker:'04 / Das Datenmodell',title:['Von Rohdaten','zum Golden Record.'],intro:'Gute Stammdaten entstehen nicht durch einen einzelnen Schritt. Sie entstehen durch definierte Prozesse, klare Regeln, Qualitätssicherung und eine belastbare technische Integration.',cards:[['01 / INPUT','Datenquellen','Geschäftspartner-, Adress-, Unternehmens- und Transaktionsdaten aus unterschiedlichen Quellen.'],['02 / QUALITY','Data Quality','Prüfen, bereinigen, strukturieren und standardisieren, bevor Daten weiterverarbeitet werden.'],['03 / MATCH','Matching','Datenbestände abgleichen, Dubletten erkennen und belastbare Golden Records definieren.'],['04 / GOVERN','Governance','Verantwortlichkeiten, Regeln und Prozesse für langfristig verlässliche Stammdaten.']]},
tech:{kicker:'05 / Technologie',title:['Technologie schafft','verlässliche Daten.'],intro:'Wir denken Daten fachlich und technisch zusammen: von der Quelle über Qualität und Matching bis zur Nutzung in ERP-, Web- und Analyseprozessen. So wird aus verteilten Informationen eine belastbare Datengrundlage.',principles:[['01','Integration','Bestehende Systeme anbinden, statt Prozesse unnötig neu zu erfinden.'],['02','Qualität','Regeln, Validierungen und Matching schaffen nachvollziehbare Datenqualität.'],['03','Transparenz','Datenflüsse und Ergebnisse so gestalten, dass sie verständlich und prüfbar bleiben.']],items:[['DATA','Master Data Management'],['QUALITY','Data Quality & Matching'],['ANALYTICS','Power BI & Analytics'],['DATABASE','MS-SQL & Datenbanken'],['INTEGRATION','ERP · Web · eCommerce'],['GOVERNANCE','Data Governance']]},
contact:{kicker:'06 / Kontakt',title:['Lassen Sie uns','Ihre Daten','in Ordnung bringen.'],intro:'Sie möchten Stammdatenprozesse optimieren, Datenbestände konsolidieren oder Ihre Data-Governance-Struktur weiterentwickeln?',cta:'[ Gespräch beginnen ]'},
footer:'PHYSOLUTION GMBH © 2026',original:'ORIGINAL WEBSITE ↗',top:'BACK TO TOP ↑'},
en:{
lang:'en',switchLabel:'DE',switchHref:'/de/',nav:['Services','About','Data model'],contact:'Contact',
hero:{kicker:'01 / Master data management',title:['Master data.','Processes.','Reliable','business relationships.'],intro:'PhySolution is a technical management consultancy and project management boutique with more than 25 years of experience in master data management.',since:'SINCE 1996 · GROß-GERAU',cta:'[ Discover services ]'},
services:{kicker:'02 / Services & capabilities',title:['Understand data.','Improve processes.'],intro:'Our core expertise is business partner master data management — from MDM and data quality to governance, analytics and golden records.',items:[['Business partner master data','Process optimisation'],['Data Quality & MDM','Quality & consolidation'],['Data Analytics','MS-SQL · Power BI · MS Office'],['Golden Records & Matching','Data consolidation'],['Data Governance','Compliance & governance'],['ERP & Web Integration','Processes & eCommerce'],['Identity & Fraud Prevention','Checks & risk data'],['Technology & know-how databases','Databases & knowledge systems']]},
about:{kicker:'03 / About PhySolution',title:['Over 25 years','of experience','with valuable data.'],paragraphs:['PhySolution GmbH was founded in 1996 by Dr. Roland Goschke, Dr. Matthias Drodt and Dr. Michael Speckmann in Groß-Gerau.','As one of the early private-sector technology transfer consultancies, the company developed technology and expert databases from an early stage.','With the internet boom of the late 1990s, process consulting around master data and application management became a major business area.','Today, PhySolution advises on master data processes, master data consolidation, database consolidation and all aspects of business partner data management.'],history:[['1996','PhySolution GmbH founded in Groß-Gerau.'],['1997','Publication of the “Know-how Germany” and “Know-how Professional” databases.'],['Today','Consulting and implementation in modern master data management.']]},
model:{kicker:'04 / The data model',title:['From raw data','to the golden record.'],intro:'Good master data does not emerge from a single step. It comes from defined processes, clear rules, quality assurance and robust technical integration.',cards:[['01 / INPUT','Data sources','Business partner, address, company and transaction data from different sources.'],['02 / QUALITY','Data Quality','Check, cleanse, structure and standardise data before further processing.'],['03 / MATCH','Matching','Compare datasets, identify duplicates and establish reliable golden records.'],['04 / GOVERN','Governance','Responsibilities, rules and processes for reliable master data over time.']]},
tech:{kicker:'05 / Technology',title:['Technology makes','data dependable.'],intro:'We connect business requirements with technical implementation: from source systems through quality and matching to ERP, web and analytics processes. The result is a reliable data foundation that can be operated and evolved.',principles:[['01','Integration','Connect existing systems and improve the process around them instead of rebuilding everything.'],['02','Quality','Rules, validation and matching create consistent and traceable data quality.'],['03','Transparency','Design data flows and results so they remain understandable and auditable.']],items:[['DATA','Master Data Management'],['QUALITY','Data Quality & Matching'],['ANALYTICS','Power BI & Analytics'],['DATABASE','MS-SQL & Databases'],['INTEGRATION','ERP · Web · eCommerce'],['GOVERNANCE','Data Governance']]},
contact:{kicker:'06 / Contact',title:['Let us put','your data','in order.'],intro:'Would you like to optimise master data processes, consolidate datasets or further develop your data governance structure?',cta:'[ Start a conversation ]'},
footer:'PHYSOLUTION GMBH © 2026',original:'ORIGINAL WEBSITE ↗',top:'BACK TO TOP ↑'}
} as const;